name: "Check PR"

on:
  pull_request:
    branches: [master]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: validate-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  changes:
    name: detect-changes
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.changes.outputs.api }}
      client: ${{ steps.changes.outputs.client }}
      shared: ${{ steps.changes.outputs.shared }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            api:
              - 'apps/api/**'
            client:
              - 'apps/client/**'
            shared:
              - '.github/workflows/check-pr.yml'
              - 'packages/**'
              - 'package.json'
              - 'yarn.lock'
              - 'turbo.json'
              - '.nvmrc'

  setup:
    name: setup
    runs-on: ubuntu-latest
    if: needs.changes.outputs.client == 'true' || needs.changes.outputs.api == 'true' || needs.changes.outputs.shared == 'true'
    needs: changes
    steps:
      - uses: actions/checkout@v6
      - name: Setup node
        uses: actions/setup-node@v6.1.0
        with:
          node-version-file: ".nvmrc"
      - name: Cache node_modules
        uses: actions/cache@v4.3.0
        id: yarn-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ github.run_id }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

  check-types:
    name: check-types
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v6
      - name: Setup node
        uses: actions/setup-node@v6.1.0
        with:
          node-version-file: ".nvmrc"
      - name: Restore cache
        uses: actions/cache@v4.3.0
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ github.run_id }}-${{ hashFiles('**/yarn.lock') }}
      - name: Check Types
        run: yarn check-types

  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v6
      - name: Setup node
        uses: actions/setup-node@v6.1.0
        with:
          node-version-file: ".nvmrc"
      - name: Restore cache
        uses: actions/cache@v4.3.0
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ github.run_id }}-${{ hashFiles('**/yarn.lock') }}
      - name: Lint Code
        run: yarn lint

  build-api:
    name: build-api
    runs-on: ubuntu-latest
    if: needs.changes.outputs.api == 'true' || needs.changes.outputs.shared == 'true'
    needs: [setup, check-types, lint, changes]
    env:
      RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup node
        uses: actions/setup-node@v6.1.0
        with:
          node-version-file: ".nvmrc"
      - name: Restore cache
        uses: actions/cache@v4.3.0
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ github.run_id }}-${{ hashFiles('**/yarn.lock') }}
      - name: Build
        run: |
          yarn global add @railway/cli
          railway link --project=${{ vars.RAILWAY_PROJECT_ID }} --service=${{ vars.RAILWAY_API_SERVICE_ID}}
          railway run yarn build --filter api

  build-client:
    name: build-client
    runs-on: ubuntu-latest
    if: needs.changes.outputs.client == 'true' || needs.changes.outputs.shared == 'true'
    needs: [setup, check-types, lint, changes]
    env:
      RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup node
        uses: actions/setup-node@v6.1.0
        with:
          node-version-file: ".nvmrc"
      - name: Restore cache
        uses: actions/cache@v4.3.0
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ github.run_id }}-${{ hashFiles('**/yarn.lock') }}
      - name: Build
        run: |
          yarn global add @railway/cli
          railway link --project=${{ vars.RAILWAY_PROJECT_ID }} --service=${{ vars.RAILWAY_CLIENT_SERVICE_ID }}
          railway run yarn build --filter client
